"""initial_schema

Revision ID: 72b795f2a03a
Revises: 
Create Date: 2026-03-26 19:26:48.741232
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
import pgvector


revision: str = '72b795f2a03a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('content_jobs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('brief', sa.JSON(), nullable=False),
    sa.Column('state', sa.String(length=50), nullable=False),
    sa.Column('draft', sa.JSON(), nullable=True),
    sa.Column('compliance_report', sa.JSON(), nullable=True),
    sa.Column('localised_versions', sa.JSON(), nullable=True),
    sa.Column('submitted_by', sa.String(length=255), nullable=True),
    sa.Column('gate_mode', sa.String(length=50), nullable=True),
    sa.Column('reviewer_decision', sa.String(length=50), nullable=True),
    sa.Column('reviewer_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_content_jobs_state'), 'content_jobs', ['state'], unique=False)
    op.create_table('documents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('doc_type', sa.String(length=50), nullable=False),
    sa.Column('raw_text', sa.Text(), nullable=True),
    sa.Column('chunk_count', sa.Integer(), nullable=True),
    sa.Column('file_size_bytes', sa.Integer(), nullable=True),
    sa.Column('uploaded_by', sa.String(length=255), nullable=True),
    sa.Column('indexed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('document_chunks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('chunk_text', sa.Text(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=384), nullable=True),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_chunks_document_id'), 'document_chunks', ['document_id'], unique=False)
    op.create_table('published_content',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('channel', sa.String(length=50), nullable=False),
    sa.Column('language', sa.String(length=10), nullable=True),
    sa.Column('published_url', sa.Text(), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('performance_score', sa.Float(), nullable=True),
    sa.Column('raw_metrics', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['content_jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_published_content_job_id'), 'published_content', ['job_id'], unique=False)
    op.create_table('stage_timings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('stage', sa.String(length=50), nullable=False),
    sa.Column('entered_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('exited_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('is_human_stage', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['content_jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stage_timings_job_id'), 'stage_timings', ['job_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stage_timings_job_id'), table_name='stage_timings')
    op.drop_table('stage_timings')
    op.drop_index(op.f('ix_published_content_job_id'), table_name='published_content')
    op.drop_table('published_content')
    op.drop_index(op.f('ix_document_chunks_document_id'), table_name='document_chunks')
    op.drop_table('document_chunks')
    op.drop_table('documents')
    op.drop_index(op.f('ix_content_jobs_state'), table_name='content_jobs')
    op.drop_table('content_jobs')
    # ### end Alembic commands ###
