import React, { useState, useEffect } from 'react';
import { 
  BarChart3, 
  BookOpen, 
  CheckCircle2, 
  ChevronRight, 
  Clock, 
  FilePlus, 
  FileText, 
  Globe, 
  Layers, 
  LayoutDashboard, 
  Loader2, 
  MessageSquare, 
  Plus, 
  Send, 
  ShieldCheck, 
  Upload, 
  XCircle,
  Zap 
} from 'lucide-react';
import axios from 'axios';

// --- Types ---
interface ContentJob {
  job_id: string;
  state: string;
  topic: string;
  created_at: string;
  brief?: any;
  draft?: { text: string };
  compliance_report?: { status: string; report: string; auto_fixes?: string };
  localised_versions?: Record<string, string>;
  violation_count?: number;
}

interface Document {
  id: string;
  filename: string;
  type: string;
  chunks: number;
}

// --- Components ---

function App() {
  const [activeTab, setActiveTab] = useState('dashboard');
  const [jobs, setJobs] = useState<ContentJob[]>([]);
  const [docs, setDocs] = useState<Document[]>([]);
  const [selectedJob, setSelectedJob] = useState<ContentJob | null>(null);
  const [loading, setLoading] = useState(false);
  const [isCreating, setIsCreating] = useState(false);
  const [metrics, setMetrics] = useState<any>({ avg_cycle_time: '0s', compliance_pass_rate: '100%', total_jobs: 0, efficiency_lift: '+24%' });
  const [extractedText, setExtractedText] = useState("");
  const [generatedContent, setGeneratedContent] = useState<{blog: string, linkedin_post: string} | null>(null);
  const [notification, setNotification] = useState<{message: string, type: 'success' | 'error'} | null>(null);
  
  const [selectedLangs, setSelectedLangs] = useState<string[]>([]);
  const [translating, setTranslating] = useState(false);
  const [translations, setTranslations] = useState<Record<string, string> | null>(null);
  const [generatedJobId, setGeneratedJobId] = useState<string | null>(null);
  const [approvedForTranslation, setApprovedForTranslation] = useState(false);

  useEffect(() => {
    if (notification) {
      const timer = setTimeout(() => setNotification(null), 5000);
      return () => clearTimeout(timer);
    }
  }, [notification]);

  // Poll for job updates and metrics
  useEffect(() => {
    const fetch = async () => {
      try {
        const [jobsRes, docsRes, metricsRes] = await Promise.all([
          axios.get('/api/jobs/list'),
          axios.get('/api/documents/list'),
          axios.get('/api/jobs/metrics')
        ]);
        setJobs(jobsRes.data);
        setDocs(docsRes.data);
        setMetrics(metricsRes.data);
      } catch (e) {
        console.error("Fetch error", e);
      }
    };
    fetch();
    const interval = setInterval(fetch, 3000);
    return () => clearInterval(interval);
  }, []);

  const handleUpload = async (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (!file) return;
    const formData = new FormData();
    formData.append('file', file);
    setLoading(true);
    try {
      const res = await axios.post('/api/documents/upload', formData);
      console.log("Upload Success", res.data);
      setNotification({ message: 'PDF Uploaded successfully! Agent pipeline initiated.', type: 'success' });
      
      if (res.data.extracted_text) {
        setExtractedText(res.data.extracted_text);
      }
      
      // Refresh docs and jobs
      const [docsRes, jobsRes] = await Promise.all([
        axios.get('/api/documents/list'),
        axios.get('/api/jobs/list')
      ]);
      setDocs(docsRes.data);
      setJobs(jobsRes.data);

      // Auto-select the new job and switch to pipeline
      if (res.data.job_id) {
        const newJob = jobsRes.data.find((j: any) => j.job_id === res.data.job_id);
        if (newJob) setSelectedJob(newJob);
        setActiveTab('pipeline');
      } else if (res.data.status === 'demo-mode') {
        const mockJob: ContentJob = {
          job_id: 'demo-job-' + Date.now(),
          state: 'draft_ready',
          topic: file.name,
          created_at: new Date().toISOString(),
          draft: { text: "Demo Draft: Your content is being generated by Groq and will appear here in a real environment." }
        };
        setSelectedJob(mockJob);
        setActiveTab('pipeline');
      }
    } catch (err: any) {
      console.error("Upload error", err);
      setNotification({ message: `Upload Failed: ${err.response?.data?.detail || err.message}`, type: 'error' });
    }
    setLoading(false);
  };

  const createJob = async (e: React.FormEvent<HTMLFormElement>) => {
    e.preventDefault();
    const fd = new FormData(e.currentTarget);
    const data = {
      topic: fd.get('topic'),
      content_format: 'blog_post',
      target_audience: 'Enterprise Tech',
      tone: 'Professional & Authoritative',
      target_languages: ['de', 'fr', 'ta'],
      gate_mode: 'async_approval',
      source_doc_ids: fd.get('doc_id') ? [fd.get('doc_id')] : []
    };
    setLoading(true);
    await axios.post('/api/jobs/create', data);
    setIsCreating(false);
    setLoading(false);
  };

  const approveJob = async (jobId: string) => {
    setLoading(true);
    try {
      const res = await axios.post(`/api/jobs/approve/${jobId}`);
      setNotification({ message: res.data.message || 'Job approved successfully!', type: 'success' });
      
      // Refresh jobs list
      const jobsRes = await axios.get('/api/jobs/list');
      setJobs(jobsRes.data);
      
      // Update selected job locally to reflect state change
      if (selectedJob && selectedJob.job_id === jobId) {
        setSelectedJob({ ...selectedJob, state: 'approved' });
      }
    } catch (err: any) {
      console.error("Approval error", err);
      setNotification({ message: `Approval failed: ${err.response?.data?.detail || err.message}`, type: 'error' });
    }
    setLoading(false);
  };

  const rejectJob = async (jobId: string) => {
    const notes = prompt("Enter rejection reason (optional):");
    setLoading(true);
    try {
      const res = await axios.post(`/api/jobs/reject/${jobId}`, { notes });
      setNotification({ message: res.data.message || 'Job rejected.', type: 'success' });
      
      // Refresh jobs list
      const jobsRes = await axios.get('/api/jobs/list');
      setJobs(jobsRes.data);
      
      if (selectedJob && selectedJob.job_id === jobId) {
        setSelectedJob({ ...selectedJob, state: 'rejected' });
      }
    } catch (err: any) {
      console.error("Rejection error", err);
      setNotification({ message: `Rejection failed: ${err.response?.data?.detail || err.message}`, type: 'error' });
    }
    setLoading(false);
  };

  const handleGenerate = async () => {
    if (!extractedText) return;
    setLoading(true);
    setNotification({ message: 'Generating content and running governance checks...', type: 'success' });
    try {
      const res = await axios.post('/api/documents/generate_content', { text: extractedText });
      setGeneratedContent(res.data);

      const returnedJobId: string | null = res.data.job_id ?? null;
      const violationCount: number = res.data.violation_count ?? 0;

      if (returnedJobId) {
        setGeneratedJobId(returnedJobId);
        // Fetch fresh jobs list then select the real job for pipeline view
        const jobsRes = await axios.get('/api/jobs/list');
        setJobs(jobsRes.data);
        const realJob = jobsRes.data.find((j: ContentJob) => j.job_id === returnedJobId);
        if (realJob) {
          setSelectedJob({
            ...realJob,
            draft: { text: res.data.blog },
            compliance_report: {
              status: res.data.governance_status === 'passed' ? 'PASS' : 'FAIL',
              report: res.data.governance_message
            },
            violation_count: violationCount
          });
        }
      }

      setActiveTab('pipeline');

      if (res.data.governance_status === 'passed') {
        setNotification({ message: `✓ Content passed governance! ${violationCount > 0 ? `(${violationCount} violation${violationCount > 1 ? 's' : ''} auto-fixed)` : ''}`, type: 'success' });
      } else {
        setNotification({ message: `⚠ Governance Warning: ${res.data.governance_message}`, type: 'error' });
      }
    } catch (err: any) {
      console.error("Generation error", err);
      setNotification({ message: `Generation failed: ${err.response?.data?.detail || err.message}`, type: 'error' });
    }
    setLoading(false);
  };

  const handleTranslate = async () => {
    if (!generatedContent || selectedLangs.length === 0) return;
    setTranslating(true);
    const langNames: Record<string, string> = { ta: 'Tamil', hi: 'Hindi', bn: 'Bengali', te: 'Telugu', ml: 'Malayalam' };
    const langList = selectedLangs.map(l => langNames[l] || l).join(', ');
    setNotification({ message: `Translating into: ${langList}…`, type: 'success' });
    try {
      const textToTranslate = "Marketing Blog:\n" + generatedContent.blog + "\n\nLinkedIn Post:\n" + generatedContent.linkedin_post;
      const res = await axios.post('/api/documents/translate', { 
        text: textToTranslate, 
        languages: selectedLangs 
      });
      setTranslations(res.data);
      setNotification({ message: `✓ Translated into ${selectedLangs.length} language${selectedLangs.length > 1 ? 's' : ''}: ${langList}`, type: 'success' });
    } catch (err: any) {
      console.error("Translation error", err);
      setNotification({ message: `Translation failed: ${err.response?.data?.detail || err.message}`, type: 'error' });
    }
    setTranslating(false);
  };

  return (
    <div className="flex h-screen bg-slate-950">
      {/* Notification Toast */}
      {notification && (
        <div className={`fixed top-4 left-1/2 -translate-x-1/2 z-[100] px-6 py-3 rounded-full shadow-2xl border backdrop-blur-md flex items-center space-x-3 transition-all animate-in slide-in-from-top-full duration-300 ${notification.type === 'success' ? 'bg-green-500/20 border-green-500/50 text-green-200' : 'bg-red-500/20 border-red-500/50 text-red-200'}`}>
          {notification.type === 'success' ? <CheckCircle2 size={18}/> : <ShieldCheck size={18}/>}
          <span className="font-semibold text-sm">{notification.message}</span>
        </div>
      )}

      {/* Sidebar */}
      <aside className="w-64 border-r border-white/5 flex flex-col p-6 space-y-8 glass">
        <div className="flex items-center space-x-3 text-brand-400">
          <Zap className="fill-brand-500" />
          <span className="font-bold text-xl tracking-tight">ContentOps AI</span>
        </div>
        
        <nav className="flex-1 space-y-1">
          <NavButton active={activeTab === 'dashboard'} onClick={() => setActiveTab('dashboard')} icon={<LayoutDashboard size={20}/>} label="Dashboard" />
          <NavButton active={activeTab === 'knowledge'} onClick={() => setActiveTab('knowledge')} icon={<BookOpen size={20}/>} label="Knowledge" />
          <NavButton active={activeTab === 'pipeline'} onClick={() => setActiveTab('pipeline')} icon={<Layers size={20}/>} label="Pipeline" />
          <NavButton active={activeTab === 'metrics'} onClick={() => setActiveTab('metrics')} icon={<BarChart3 size={20}/>} label="Analytics" />
        </nav>

        <div className="p-4 rounded-xl bg-gradient-to-br from-brand-600/20 to-purple-600/20 border border-brand-500/20">
          <p className="text-xs text-brand-200 font-medium mb-1">System Status</p>
          <div className="flex items-center space-x-2">
            <div className="w-2 h-2 rounded-full bg-green-500 animate-pulse" />
            <span className="text-sm font-semibold">Agents Online</span>
          </div>
        </div>
      </aside>

      {/* Main Content */}
      <main className="flex-1 flex flex-col overflow-hidden">
        <header className="h-16 border-b border-white/5 flex items-center justify-between px-8 bg-slate-900/50 backdrop-blur-sm">
          <h1 className="text-lg font-semibold capitalize text-slate-300">{activeTab}</h1>
          <div className="flex items-center space-x-4">
             {loading && <Loader2 className="animate-spin text-brand-400" size={18} />}
             <button 
                onClick={() => setIsCreating(true)}
                className="flex items-center space-x-2 bg-brand-600 hover:bg-brand-500 text-white px-4 py-2 rounded-lg font-medium transition-all shadow-lg shadow-brand-500/20 active:scale-95">
               <Plus size={18} />
               <span>New Brief</span>
             </button>
          </div>
        </header>

        <div className="flex-1 overflow-y-auto p-8">
          {activeTab === 'dashboard' && (
            <div className="space-y-8">
              {/* Stats Grid */}
              <div className="grid grid-cols-4 gap-6">
                <StatCard label="Total Jobs" value={metrics.total_jobs} icon={<Layers className="text-blue-400"/>} trend="+12%"/>
                <StatCard label="Live Pipelines" value={jobs.filter(j => !['completed', 'published'].includes(j.state)).length} icon={<Zap className="text-yellow-400"/>} trend="Active"/>
                <StatCard label="Compliance Rate" value={metrics.compliance_pass_rate} icon={<ShieldCheck className="text-green-400"/>} trend="Stable"/>
                <StatCard label="Avg. Cycle Time" value={metrics.avg_cycle_time} icon={<Clock className="text-purple-400"/>} trend="-4s"/>
              </div>

              {/* Main Feed */}
              <div className="grid grid-cols-3 gap-8">
                <div className="col-span-2 space-y-4">
                  <h2 className="text-sm font-bold uppercase tracking-widest text-slate-500">Recent Activity</h2>
                  {jobs.length === 0 ? (
                    <div className="card h-64 flex flex-col items-center justify-center space-y-4 border-dashed border-white/10">
                      <div className="p-4 bg-white/5 rounded-full"><Plus className="text-slate-600"/></div>
                      <p className="text-slate-500 font-medium">No active jobs. Create a brief to start.</p>
                    </div>
                  ) : (
                    <div className="space-y-3">
                      {jobs.map(job => (
                        <div 
                          key={job.job_id} 
                          onClick={() => setSelectedJob(job)}
                          className={`card p-4 flex items-center justify-between cursor-pointer ${selectedJob?.job_id === job.job_id ? 'ring-2 ring-brand-500/50' : ''}`}
                        >
                          <div className="flex items-center space-x-4">
                             <div className={`p-2 rounded-lg ${getStatusColor(job.state)}`}>
                               {getStatusIcon(job.state)}
                             </div>
                             <div>
                               <h3 className="font-semibold text-slate-200">{job.topic}</h3>
                               <p className="text-xs text-slate-500">{new Date(job.created_at).toLocaleString()}</p>
                             </div>
                          </div>
                          <div className="flex items-center space-x-4">
                             <span className="text-xs font-bold uppercase py-1 px-2 bg-white/5 rounded border border-white/10 text-slate-400">
                               {job.state.replace('_', ' ')}
                             </span>
                             <ChevronRight size={16} className="text-slate-600" />
                          </div>
                        </div>
                      ))}
                    </div>
                  )}
                </div>

                <div className="space-y-4">
                  <h2 className="text-sm font-bold uppercase tracking-widest text-slate-500">Knowledge Base</h2>
                  <div className="card p-6 space-y-6">
                    <label className="flex flex-col items-center justify-center p-6 border-2 border-dashed border-white/10 rounded-xl cursor-pointer hover:border-brand-500/50 transition-all bg-white/5">
                      <Upload className="text-slate-500 mb-2"/>
                      <span className="text-sm font-medium text-slate-400">Upload Product Spec</span>
                      <input type="file" className="hidden" onChange={handleUpload} accept=".pdf"/>
                    </label>
                    <div className="space-y-3">
                      {docs.map(doc => (
                        <div key={doc.id} className="flex items-center justify-between p-2 rounded hover:bg-white/5 transition-colors">
                          <div className="flex items-center space-x-3">
                            <FileText size={16} className="text-brand-400"/>
                            <span className="text-sm text-slate-300 truncate w-32">{doc.filename}</span>
                          </div>
                          <span className="text-[10px] font-bold text-slate-600 uppercase">{doc.chunks} Indexeds</span>
                        </div>
                      ))}
                    </div>
                  </div>
                </div>
              </div>
            </div>
          )}

          {activeTab === 'knowledge' && (
            <div className="space-y-8 animate-in fade-in duration-500">
               <div className="flex items-center justify-between">
                  <h2 className="text-2xl font-bold">Knowledge Management</h2>
                  <label className="flex items-center space-x-2 bg-brand-600 hover:bg-brand-500 text-white px-4 py-2 rounded-lg font-medium cursor-pointer transition-all">
                    <Upload size={18} />
                    <span>Upload PDF Spec</span>
                    <input type="file" className="hidden" onChange={handleUpload} accept=".pdf"/>
                  </label>
               </div>

               {extractedText && (
                 <div className="grid grid-cols-2 gap-8">
                   <div className="card p-6 space-y-4">
                     <h3 className="font-bold text-slate-400 flex items-center space-x-2">
                       <FileText size={18}/>
                       <span>Extracted Specification</span>
                     </h3>
                     <div className="bg-slate-900/50 p-4 rounded-lg border border-white/5 max-h-[400px] overflow-y-auto text-sm text-slate-400 font-mono">
                       {extractedText}
                     </div>
                     <button 
                        onClick={handleGenerate}
                        disabled={loading}
                        className="w-full bg-brand-600 hover:bg-brand-500 text-white p-3 rounded-xl font-bold transition-all flex items-center justify-center space-x-2">
                        {loading ? <Loader2 className="animate-spin"/> : <Zap size={18}/>}
                        <span>Generate Content with Groq</span>
                     </button>
                   </div>

                   <div className="card p-6 space-y-4">
                     <h3 className="font-bold text-slate-400 flex items-center space-x-2">
                       <Send size={18}/>
                       <span>Groq AI Output</span>
                     </h3>
                     {generatedContent ? (
                       <div className="space-y-6">
                         <div className="space-y-2">
                           <h4 className="text-xs font-bold text-brand-400 uppercase tracking-widest">Marketing Blog</h4>
                           <div className="bg-slate-900/50 p-4 rounded-lg border border-white/5 text-sm text-slate-300 max-h-[200px] overflow-y-auto">
                             {generatedContent.blog}
                           </div>
                         </div>
                         <div className="space-y-2">
                           <h4 className="text-xs font-bold text-brand-400 uppercase tracking-widest">LinkedIn Post</h4>
                           <div className="bg-slate-900/50 p-4 rounded-lg border border-white/5 text-sm text-slate-300 max-h-[150px] overflow-y-auto">
                             {generatedContent.linkedin_post}
                           </div>
                         </div>
                       </div>
                     ) : (
                       <div className="h-64 flex items-center justify-center text-slate-600 italic">
                         Click "Generate" to create marketing assets
                       </div>
                      )}
                    </div>
                  </div>
                )}
                
                {generatedContent && (
                  <div id="translation-section" className="card p-6 space-y-6 border-purple-500/20 bg-purple-900/10">
                    <h3 className="font-bold text-purple-400 flex items-center space-x-2">
                      <Globe size={18} />
                      <span>Localize Content — Indian Languages</span>
                    </h3>
                    <div className="flex items-center space-x-3 flex-wrap gap-y-3">
                      {[
                        { code: 'ta', name: 'Tamil', flag: '🇮🇳' },
                        { code: 'hi', name: 'Hindi', flag: '🇮🇳' },
                        { code: 'bn', name: 'Bengali', flag: '🇧🇩' },
                        { code: 'te', name: 'Telugu', flag: '🇮🇳' },
                        { code: 'ml', name: 'Malayalam', flag: '🇮🇳' },
                      ].map(({ code, name, flag }) => (
                        <label key={code} className={`flex items-center space-x-2 cursor-pointer px-3 py-2 rounded-lg border transition-all ${selectedLangs.includes(code) ? 'border-purple-500 bg-purple-500/20 text-purple-200' : 'border-white/10 hover:bg-white/5 text-slate-400'}`}>
                          <input type="checkbox" className="hidden" checked={selectedLangs.includes(code)} onChange={() => {
                            setSelectedLangs(prev => prev.includes(code) ? prev.filter(l => l !== code) : [...prev, code]);
                          }} />
                          <span>{flag}</span>
                          <span className="font-bold text-sm">{name}</span>
                        </label>
                      ))}
                      <button onClick={handleTranslate} disabled={translating || selectedLangs.length === 0} className="ml-auto bg-purple-600 hover:bg-purple-500 disabled:opacity-50 text-white px-4 py-2 rounded-lg font-bold flex items-center space-x-2 transition-all active:scale-95">
                        {translating ? <Loader2 size={16} className="animate-spin" /> : <Send size={16} />}
                        <span>{translating ? 'Translating...' : 'Translate Selected'}</span>
                      </button>
                    </div>
                    {translating && (
                      <div className="flex items-center space-x-3 text-purple-300 text-sm font-medium animate-pulse">
                        <Loader2 size={16} className="animate-spin" />
                        <span>Groq is translating into {selectedLangs.length} language{selectedLangs.length > 1 ? 's' : ''}…</span>
                      </div>
                    )}
                    {translations && Object.keys(translations).length > 0 && (
                      <div className="grid grid-cols-1 gap-4">
                        {Object.entries(translations).map(([lang, text]) => {
                          const langNames: Record<string, string> = { ta: 'Tamil 🇮🇳', hi: 'Hindi 🇮🇳', bn: 'Bengali 🇧🇩', te: 'Telugu 🇮🇳', ml: 'Malayalam 🇮🇳' };
                          return (
                            <div key={lang} className="bg-slate-900/80 p-4 rounded-xl border border-purple-500/20 space-y-2">
                              <div className="flex items-center justify-between">
                                <h4 className="text-sm font-bold text-purple-400">{langNames[lang] || lang.toUpperCase()}</h4>
                                <CheckCircle2 size={14} className="text-green-500" />
                              </div>
                              <div className="text-sm text-slate-300 max-h-[200px] overflow-y-auto whitespace-pre-wrap leading-relaxed">
                                {text}
                              </div>
                            </div>
                          );
                        })}
                      </div>
                    )}
                  </div>
                )}

                <div className="grid grid-cols-4 gap-4">
                 {docs.map(doc => (
                   <div key={doc.id} className="card p-4 space-y-3 hover:border-brand-500/30 transition-all group">
                     <div className="flex items-center justify-between">
                       <div className="p-2 bg-brand-500/10 rounded-lg text-brand-400 group-hover:scale-105 transition-transform"><FileText size={18}/></div>
                       <span className="text-[9px] font-bold bg-white/5 py-0.5 px-1.5 rounded uppercase text-slate-500">{doc.type}</span>
                     </div>
                     <div>
                       <h3 className="font-bold text-sm text-slate-200 truncate">{doc.filename}</h3>
                       <p className="text-[10px] text-slate-500">{doc.chunks} Semantic Chunks</p>
                     </div>
                   </div>
                 ))}
               </div>
               {docs.length === 0 && (
                 <div className="card h-64 flex flex-col items-center justify-center border-dashed border-white/10 text-slate-600 space-y-2">
                   <FileText size={48} className="opacity-20"/>
                   <p>No documents indexed yet.</p>
                 </div>
               )}
            </div>
          )}
          {activeTab === 'pipeline' && (
             <div className="flex flex-col items-center justify-center h-full space-y-6">
                {!selectedJob ? (
                  <p className="text-slate-500">Select a job from Dashboard to view real-time pipeline telemetry.</p>
                ) : (
                  <div className="w-full max-w-4xl space-y-8 animate-in fade-in slide-in-from-bottom-4 duration-500">
                     <div className="flex items-center justify-between">
                        <div>
                          <h2 className="text-2xl font-bold">{selectedJob.topic}</h2>
                          <p className="text-slate-500">Job ID: {selectedJob.job_id}</p>
                        </div>
                        <div className="flex items-center space-x-3">
                           {selectedJob.state === 'human_review' && (
                             <button 
                                onClick={() => approveJob(selectedJob.job_id)}
                                className="bg-green-600 hover:bg-green-500 text-white px-6 py-2 rounded-full font-bold shadow-lg shadow-green-500/20 flex items-center space-x-2 active:scale-95 transition-all">
                               <CheckCircle2 size={18} />
                               <span>Approve & Publish</span>
                             </button>
                           )}
                        </div>
                     </div>

                      {/* Progress Stepper */}
                      <div className="flex items-center justify-between bg-white/5 p-8 rounded-3xl border border-white/10 shadow-2xl relative overflow-hidden">
                        <div className="absolute inset-0 bg-gradient-to-r from-brand-500/5 to-transparent pointer-events-none" />
                        <Step label="Brief" active={true} completed={true} />
                        <Divider active={true} />
                        <Step label="Strategy" active={['strategy_adjustment', 'retrieving', 'drafting', 'draft_ready', 'compliance_check', 'human_review', 'approved', 'localising', 'scheduling', 'published', 'completed'].includes(selectedJob.state)} completed={['retrieving', 'drafting', 'draft_ready', 'compliance_check', 'human_review', 'approved', 'localising', 'scheduling', 'published', 'completed'].includes(selectedJob.state)} />
                        <Divider active={['retrieving', 'drafting', 'draft_ready', 'compliance_check', 'human_review', 'approved', 'localising', 'scheduling', 'published', 'completed'].includes(selectedJob.state)} />
                        <Step label="Context" active={['retrieving', 'drafting', 'draft_ready', 'compliance_check', 'human_review', 'approved', 'localising', 'scheduling', 'published', 'completed'].includes(selectedJob.state)} completed={['drafting', 'draft_ready', 'compliance_check', 'human_review', 'approved', 'localising', 'scheduling', 'published', 'completed'].includes(selectedJob.state)} />
                        <Divider active={['drafting', 'draft_ready', 'compliance_check', 'human_review', 'approved', 'localising', 'scheduling', 'published', 'completed'].includes(selectedJob.state)} />
                        <Step label="Drafting" active={['drafting', 'draft_ready', 'compliance_check', 'human_review', 'approved', 'localising', 'scheduling', 'published', 'completed'].includes(selectedJob.state)} completed={['draft_ready', 'compliance_check', 'human_review', 'approved', 'localising', 'scheduling', 'published', 'completed'].includes(selectedJob.state)} />
                        <Divider active={['draft_ready', 'compliance_check', 'human_review', 'approved', 'localising', 'scheduling', 'published', 'completed'].includes(selectedJob.state)} />
                        <Step label="Governance" active={['compliance_check', 'human_review', 'approved', 'localising', 'scheduling', 'published', 'completed'].includes(selectedJob.state)} completed={['human_review', 'approved', 'localising', 'scheduling', 'published', 'completed'].includes(selectedJob.state)} />
                        <Divider active={['human_review', 'approved', 'localising', 'scheduling', 'published', 'completed'].includes(selectedJob.state)} />
                        <Step label="Publish" active={['published', 'completed'].includes(selectedJob.state)} completed={selectedJob.state === 'completed'} />
                      </div>

                      {selectedJob.compliance_report && (
                         <div className={`w-full p-6 rounded-2xl flex items-start space-x-4 animate-in fade-in zoom-in-95 relative z-10 shadow-lg ${selectedJob.compliance_report.status === 'PASS' ? 'bg-green-500/10 border border-green-500/20 shadow-green-500/5' : 'bg-red-500/10 border border-red-500/20 shadow-red-500/5'}`}>
                            <ShieldCheck size={28} className={`shrink-0 ${selectedJob.compliance_report.status === 'PASS' ? 'text-green-500' : 'text-red-400'}`}/>
                            <div className="space-y-2 w-full">
                               <div className="flex items-center justify-between w-full flex-wrap gap-2">
                                 <h3 className={`font-bold ${selectedJob.compliance_report.status === 'PASS' ? 'text-green-400' : 'text-red-400'}`}>
                                   Governance Policy Check: {selectedJob.compliance_report.status}
                                 </h3>
                                 <div className="flex items-center gap-2 flex-wrap">
                                   {(selectedJob.violation_count ?? 0) > 0 && (
                                     <div className="flex items-center space-x-2 bg-orange-500/20 border border-orange-500/50 px-3 py-1 rounded-full">
                                       <ShieldCheck size={14} className="text-orange-400" />
                                       <span className="text-xs font-bold text-orange-200">
                                         {selectedJob.violation_count} violation{(selectedJob.violation_count ?? 0) > 1 ? 's' : ''} auto-fixed
                                       </span>
                                     </div>
                                   )}
                                   {selectedJob.compliance_report.status === 'PASS' && (selectedJob.violation_count ?? 0) === 0 && (
                                     <div className="flex items-center space-x-2 bg-green-500/20 border border-green-500/50 px-3 py-1 rounded-full">
                                       <CheckCircle2 size={14} className="text-green-400" />
                                       <span className="text-xs font-bold text-green-200">0 violations</span>
                                     </div>
                                   )}
                                 </div>
                               </div>
                               <p className={`text-sm leading-relaxed font-medium ${selectedJob.compliance_report.status === 'PASS' ? 'text-green-200/80' : 'text-red-200/80'}`}>
                                 {selectedJob.compliance_report.report}
                               </p>
                            </div>
                         </div>
                      )}

                      {/* CTA Banner for translation */}
                      {selectedJob.compliance_report?.status === 'PASS' && !approvedForTranslation && (
                        <div className="w-full bg-gradient-to-r from-emerald-500/10 to-cyan-500/10 border border-emerald-500/30 p-6 rounded-2xl flex items-center justify-between mb-8 animate-in fade-in slide-in-from-bottom-2 duration-500">
                          <div className="space-y-1">
                            <p className="font-bold text-emerald-400 text-sm uppercase tracking-widest">✓ Final Verification Complete</p>
                            <p className="text-slate-300 text-sm">Review finished. Click below to start the localization process.</p>
                          </div>
                          <button
                            onClick={() => {
                              setApprovedForTranslation(true);
                              setActiveTab('knowledge');
                              setTimeout(() => {
                                document.getElementById('translation-section')?.scrollIntoView({ behavior: 'smooth', block: 'start' });
                              }, 150);
                            }}
                            className="flex items-center space-x-2 bg-gradient-to-r from-green-600 to-emerald-500 hover:from-green-500 hover:to-emerald-400 text-white px-6 py-3 rounded-xl font-bold shadow-lg shadow-green-500/30 active:scale-95 transition-all">
                            <Globe size={18} />
                            <span>Approve & Translate</span>
                          </button>
                        </div>
                      )}


                  </div>
                )}
             </div>
          )}
        </div>
      </main>

      {/* Create Brief Modal */}
      {isCreating && (
        <div className="fixed inset-0 bg-slate-950/80 backdrop-blur-sm flex items-center justify-center z-50 p-4">
           <form onSubmit={createJob} className="card w-full max-w-lg p-8 space-y-6 animate-in zoom-in-95 duration-200">
              <div className="flex items-center justify-between">
                 <h2 className="text-2xl font-bold">New Content Brief</h2>
                 <button onClick={() => setIsCreating(false)} className="text-slate-500 hover:text-white">Close</button>
              </div>
              <div className="space-y-4">
                 <div className="space-y-2">
                    <label className="text-sm font-bold text-slate-500 uppercase">Primary Topic</label>
                    <input name="topic" required className="w-full bg-white/5 border border-white/10 rounded-lg p-3 outline-none focus:border-brand-500" placeholder="e.g. Next-Gen Agentic Workflows" />
                 </div>
                 <div className="space-y-2">
                    <label className="text-sm font-bold text-slate-500 uppercase">Context Document</label>
                    <select name="doc_id" className="w-full bg-white/5 border border-white/10 rounded-lg p-3 outline-none focus:border-brand-500 text-slate-300">
                      <option value="">No Document (General Topic)</option>
                      {docs.map(doc => (
                        <option key={doc.id} value={doc.id}>{doc.filename}</option>
                      ))}
                    </select>
                  </div>
                 <div className="grid grid-cols-2 gap-4">
                    <div className="space-y-2">
                      <label className="text-sm font-bold text-slate-500 uppercase">Target Channels</label>
                      <div className="flex space-x-2">
                        <span className="bg-brand-500/20 text-brand-400 px-2 py-1 rounded text-xs font-bold">CMS</span>
                        <span className="bg-brand-500/20 text-brand-400 px-2 py-1 rounded text-xs font-bold">LinkedIn</span>
                      </div>
                    </div>
                    <div className="space-y-2">
                      <label className="text-sm font-bold text-slate-500 uppercase">Languages</label>
                      <div className="flex space-x-2">
                        <span className="bg-white/5 px-2 py-1 rounded text-xs font-bold uppercase">DE</span>
                        <span className="bg-white/5 px-2 py-1 rounded text-xs font-bold uppercase">FR</span>
                        <span className="bg-white/5 px-2 py-1 rounded text-xs font-bold uppercase">TA</span>
                      </div>
                    </div>
                 </div>
              </div>
              <button 
                type="submit"
                disabled={loading}
                className="w-full bg-brand-600 hover:bg-brand-500 text-white p-4 rounded-xl font-bold text-lg shadow-xl shadow-brand-500/20 transition-all flex items-center justify-center space-x-2">
                {loading ? <Loader2 className="animate-spin"/> : <Zap size={20}/>}
                <span>Initiate Agentic Pipeline</span>
              </button>
           </form>
        </div>
      )}
    </div>
  );
}

// --- Subcomponents ---

function NavButton({ active, icon, label, onClick }: any) {
  return (
    <button onClick={onClick} className={`w-full flex items-center space-x-3 p-3 rounded-xl transition-all ${active ? 'bg-brand-600/10 text-brand-400 border border-brand-500/20 shadow-inner shadow-brand-500/10' : 'text-slate-500 hover:text-slate-300 hover:bg-white/5'}`}>
      {icon}
      <span className="font-semibold">{label}</span>
    </button>
  );
}

function StatCard({ label, value, icon, trend }: any) {
  return (
    <div className="card p-6 space-y-3">
       <div className="flex items-center justify-between">
          <div className="p-2 bg-white/5 rounded-lg">{icon}</div>
          <span className={`text-[10px] font-bold px-2 py-0.5 rounded ${trend.startsWith('+') || trend === 'Active' ? 'bg-green-500/10 text-green-500' : 'bg-slate-500/10 text-slate-400'}`}>{trend}</span>
       </div>
       <div>
          <p className="text-xs font-bold text-slate-500 uppercase tracking-widest">{label}</p>
          <h3 className="text-2xl font-bold text-slate-100">{value}</h3>
       </div>
    </div>
  );
}

function Step({ label, active, completed }: any) {
  return (
    <div className="flex flex-col items-center space-y-2 relative">
       <div className={`w-12 h-12 rounded-full flex items-center justify-center border-2 transition-all duration-500 ${completed ? 'bg-brand-500 border-brand-500 text-white shadow-lg shadow-brand-500/40' : active ? 'border-brand-500 text-brand-500 animate-pulse' : 'border-white/10 text-slate-700'}`}>
         {completed ? <CheckCircle2 size={24}/> : <div className={`w-3 h-3 rounded-full ${active ? 'bg-brand-500' : 'bg-slate-800'}`} />}
       </div>
       <span className={`text-xs font-bold uppercase tracking-widest ${active ? 'text-slate-200' : 'text-slate-700'}`}>{label}</span>
    </div>
  );
}

function Divider({ active }: any) {
  return (
    <div className="flex-1 px-4">
       <div className={`h-0.5 w-full rounded-full transition-all duration-1000 ${active ? 'bg-brand-500/50' : 'bg-white/5'}`} />
    </div>
  );
}

function getStatusIcon(state: string) {
  switch (state) {
    case 'completed':
    case 'published': return <CheckCircle2 size={18} />;
    case 'human_review': return <MessageSquare size={18} />;
    case 'failed': return <ShieldCheck size={18} />;
    default: return <Loader2 size={18} className="animate-spin" />;
  }
}

function getStatusColor(state: string) {
  switch (state) {
    case 'completed':
    case 'published': return 'bg-green-500/10 text-green-500';
    case 'human_review': return 'bg-brand-500/10 text-brand-500';
    case 'failed': return 'bg-red-500/10 text-red-500';
    default: return 'bg-yellow-500/10 text-yellow-500';
  }
}

export default App;
